language: node_js

node_js:
  - 'stable'
  - 'lts/*'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - 'npm i -g gatsby-cli'

script:
  - gatsby build

notifications:
  webhooks:
    - https://webhooks.datocms.com/FnPF9L4Ooi/deploy-results
