language: node_js
node_js:
  - stable
  - lts/*
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_script:
  - npm i -g gatsby-cli
script:
  - gatsby build
notifications:
  webhooks:
    - https://webhooks.datocms.com/FnPF9L4Ooi/deploy-results
deploy:
  api_key:
    secure: UBG86hMkbIdBmPFMtm+K2sszIa4pJxpokIMo3ssjkLjwFwD3SF71ePuqcxGXCV6AmaVIuRur/lj60q6w4ppzpflyRAUpPd8PwGiHSklkLgW4VzRi1T+M09Ptvrjos6M9fTIWMyOGF00KDhc65A+r4pdtOPFJtAXsRp8+hB2335t8jLxuZk9nglBGUfyt/52sNwSyxOY6SCBQlrpchi9qsE4X9Zwurt8g1tsOn9HMdqlkCyWdaut5ggQMQ/Hzw2xWRbV5RCJD6pH4xFQa/9klKrL2iwd+N+ml9xleesLkcYcRHdg2ex6dBaLnBUECpWe/xFeYLWNqHFNgQSWDuwE26IauZQArNKzDt6s5qQiCKe12QC+pk+kVWoT+AwyBR6y8c1C7dcL4kaj37TAU9H+WBaOgKhGNdxIQdJeqFmagzkOCcY0V8QXArVXAGajoxQ7D4PO07j7M27adgoAM6LxiZd4OId8jDWHxN2v2z98MM+3nJcwAVDZKTq5w7ATqzIvqIzyEduYE+N2PzYta0oFumb9C82A56Mchj2I2KQaDC6xMmi/ea1OGkUyMURbQSDqSzl1iPClE0yAKkldidMyk59KBGn3Qmn4UOkfRSH/YVkfuGhmJnaMsbS/vFMxDwgdKwBOPbeVpc6LRJ20MtzVjklsTrfYbWrx13pPGlGB/kUg=
