language: node_js

node_js:
  - 'stable'
  - 'lts/*'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - 'npm i -g gatsby-cli'

script:
  - gatsby build

# deploy:
#   provider: heroku
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
#   keep-history: true
#   local-dir: public
#   on:
#     branch: master

notifications:
  webhooks:
    - https://webhooks.datocms.com/FnPF9L4Ooi/deploy-results
