language: node_js
node_js:
- stable
- lts/*
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_script:
- npm i -g gatsby-cli
script:
- gatsby build
deploy:
provider: heroku
  api_key:
    secure: GRQllEnpXqBJ/mcyIwSIN3goVct1EMThPaCq/ZWKnVMyD6PXRwt9WtdcLE2svIMiKaqN4cn3pjl+UVzcMqixfnwGG+aS8HhuSxjkD3oZDC9ndsyHi8BOV41/c2mxLG/zhl0+uWzY7QNwiic+z172w1Xo0vxVML7FD8TIULdRzaBNKUxgCEYlJylGvNLrzqTNJf2x1BtOvH9+lfi7KUiDtwJ2UdkOtAOV11gTArYAxUTbyNWlweZGhQC1lvzDnhoAPUGeF7lvzn7ME0IoVScRvJkpWcAbROjRPUuRTO9BhcDSHGMPW5iv+6vJ43Dm96/MapqQTfdnm04qC/bB7z8EjbijZGKWnsbxCUR51PiyvNT/bKs7TBFxqre9A5NiXVEvpXqSYxAd9+QP4CbjOObaPtJ/mA+BV6GdJG9I4MatnZmK2Utd4s/JaC8IxnWBzv3VE4MKMw5BUKvO82mIDU5pFDD6UrvBkS8rBguxBpWk3zFyj89d7obBP9LX56TUvi20A+xsvGVdnYslxTkjbsC6KrJoBkmvvwmJqTm4LdSIfUcUTCpiZ11AIADBWQdecsx9UtRVwtEZ8MCLNZCZEvHiJhphEHd1ihYbVSmiuHFFi+sn1V8IL0xMIhlpXj8JywO+2k3WIHlWDJOYDduNOJ+3ugAFxjL540U93+Q8JzqSqJA=
  app: afv-vad
  on:
    repo: clkent/VAD
notifications:
  webhooks:
    - https://webhooks.datocms.com/FnPF9L4Ooi/deploy-results