language: node_js
node_js:
  - stable
  - lts/*
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_script:
  - npm i -g gatsby-cli
script:
  - gatsby build
notifications:
  webhooks:
    - https://webhooks.datocms.com/FnPF9L4Ooi/deploy-results
deploy:
  provider: heroku
  api_key:
    secure: Q+08mFBq4nCWso9loZyqt2ctDYqYuwN1SnD7cKM8NXRYNhURI4Qmn9O3I/DZ7bY2oFTpdWfjR2smd3DQhLBpjRdzGQzdN0vgGf1v40bj/mI+mUbAnpGWa3bhn3G34KUjll8wJ2ss4xX2P+n4hBLz2KA0Xmi25w/E1WcVgTk5Sct1tB/jlFdPCs074TmUKUekcKVp5yFJwv5Xd0IBA6+jXJRrTcCzxsdmS6WaH+Jc0kWUwzVo7UgBxuD/xAW6b33NSNNlaLOg4KMiQvaAFMagh08SD4u43ctZtj3i5I9zxXsogSAME2yNHa0YnTQbOpfC3hM30k9D1LhqeAeHlL/VRrRXj35ivCPovAQ/Uwb5aOn4dhInUvl0aiKskEIsezW+UZbDbL+fDLn4L+67kAWFsLCQJwnTK3Yp3SyAewPhVVVPhUGvsnBjqr+NfUbfXw0z29ehweMrjjN8yX/+8iGsm0bxz83mFdQyTVNKp0ajzLbC9pMtYmrYbYQ5SBiM+nA4SV1/m63+BmrZhVy5jpPAU6WSejweyRgIh3ztl85UiDPYrBKk2tcPCyl+NI6by+X2fXYbYx5c3/RhuzibSkx2Ja0M4yownHSTI5T5R9JkJd0X0NnJwV4Xzpeu5norXY4m2Swvs5wauLxUINhSyd0HMp1OeROeErC3B3rT1wK6yD0=
  app: afv-vad
  on:
    repo: clkent/VAD
