language: node_js
node_js:
  - stable
  - lts/*
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_script:
  - npm i -g gatsby-cli
script:
  - gatsby build
notifications:
  webhooks:
    - https://webhooks.datocms.com/FnPF9L4Ooi/deploy-results
deploy:
  provider: heroku
  api_key:
    secure: FL8Q1A4j7Et2gzvV/hMymJmxZhWuhvkgY0bfR01O8Iuuh2f0ZwSrIZtNmkHWR1Xv8YHw0Hr+i5YiIW9oCaGhx/xzzAMVcn5tSl3iP+A94tCIAeh+2sN/yFG/3ISkRfCGZQPrlh5XL0lmY4yeNQc38TsJr+sVcz4PkKG5nVgOUlYvzonJNsEERj0nDtsATJH4/Nq+P+X0cM+A68bLOLpC14lZ0/XeSuFxUCLbCYx2tgF02yciLcszcbXW+NNUf24LnGEe3EIrizqdto13XeL4To1SqNVZWvToG2b3cGSmVEG1xcIBRFm+ARWlkIi/mS/AHevQwypGyfjBa6paE1aoqKKVN+BCdYUbdU6eHvZhTrC0uBa6nEGyuQlsPffPf8SowQBD0UwwvfETzpn7vj8YJjSGUPoy7Hi66+25WwN+rE1jMaEFod+ZaSpKnvk8TpHQmp8jZChcUL8Z44oy+czkQmIgir+dkx+GOeqYRwElABE6/DASIbqYDz9gVXJRVnRZ8Mq2bDqOvhzrDgrPPPbbvieYu5c6kMpwVc9lrYtWsElyLUp9d6jfTJ/sPYNAIisOnHbW/Qf1BmQp7WN6m6ByWFr523QXSOAgrQgbbAWJKoNBBlWH0/WTigpdQ0FBVh0zml2uAPNYpiA0pOHpbVbbqJNfl9wAct/PX3gEw7E5Q2g=
